---
# This file tells https://pre-commit.com/
# which hooks are provided by this repo
# for use by other git repos.

- id: git-check
  name: Check for conflict markers and core.whitespace errors
  # yamllint disable-line rule:line-length
  description: Use git to check for conflict markers and core.whitespace errors, respecting .gitattributes
  entry: pre_commit_hooks/git-check.sh
  language: script

- id: git-dirty
  name: Check if the git tree is dirty
  description: Detect if git tree contains modified, staged, or untracked files
  entry: pre_commit_hooks/git-dirty.sh
  language: script

- id: shellcheck
  name: Test shell scripts with shellcheck
  description: Shell scripts (based on mime type) conform to shellcheck
  entry: pre_commit_hooks/shellcheck.sh
  language: script
  additional_dependencies: ['bash', 'file', 'shellcheck']
