---
# This file tells https://pre-commit.com/
# which hooks are provided by this repo
# for use by other git repos.

- id: bundler-audit
  name: Patch-level verification for bundler
  description: Check for vulnerable gem versions and insecure sources
  entry: run-bundle-audit
  language: ruby
  pass_filenames: false
  files: Gemfile.lock
  args: [--update]

- id: check-mailmap
  name: Detect if an email address needs to be added to mailmap
  language: script
  entry: pre_commit_hooks/check-mailmap
  always_run: true  # Run on every commit.
  exclude: .*       # Otherwise runs once per file.

- id: fasterer
  name: Suggest speed improvements in Ruby
  description: Use fasterer to suggest speed improvements in Ruby
  entry: run-fasterer
  language: ruby
  types: ['ruby']

- id: forbid-binary
  name: Forbid binaries
  description: Forbid binary files from being committed
  entry: pre_commit_hooks/forbid-binary
  language: script
  types: ['binary']

- id: forbid-space-in-indent
  name: Forbid spaces in indentation
  description: Forbid spaces in indentation
  entry: pre_commit_hooks/forbid-space-in-indent
  language: script

- id: git-check
  name: Check for conflict markers and core.whitespace errors
  # yamllint disable-line rule:line-length
  description: Use git to check for conflict markers and core.whitespace errors, respecting .gitattributes
  entry: pre_commit_hooks/git-check
  language: script

- id: git-dirty
  name: Check if the git tree is dirty
  description: Detect if git tree contains modified, staged, or untracked files
  entry: pre_commit_hooks/git-dirty
  language: script

- id: markdownlint
  name: Check markdown files
  description: Check markdown files and flag style issues
  entry: run-mdl
  language: ruby
  types: ['markdown']

- id: reek
  name: Find ruby code smells
  description: Use reek to find ruby code smells
  entry: run-reek
  language: ruby
  types: ['ruby']

- id: require-ascii
  name: Check file encoding
  description: Ensure file is ascii-encoded
  entry: require-ascii.py
  language: python
  types: [text]
  additional_dependencies: [chardet]

- id: rubocop
  name: Check Ruby style with rubocop and rubocop-rspec
  description: Enforce Ruby style guide with rubocop and rubocop-rspec
  entry: run-rubocop
  language: ruby
  types: ['ruby']

- id: shellcheck
  name: Test shell scripts with shellcheck
  description: Shell scripts conform to shellcheck
  entry: pre_commit_hooks/shellcheck
  language: script
  types: [shell]
  args: [-e, SC1091]
  additional_dependencies: [shellcheck]

- id: script-must-have-extension
  name: Non-executable shell script filename ends in .sh
  description: Non-executable shell script filename ends in .sh
  entry: pre_commit_hooks/script_must_have_extension
  language: script
  types: [shell, non-executable]

- id: script-must-not-have-extension
  name: Executable shell script omits the filename extension
  description: Executable shell script omits the filename extension
  entry: pre_commit_hooks/script_must_not_have_extension
  language: script
  types: [shell, executable]

- id: shfmt
  name: Check shell style with shfmt
  language: script
  entry: pre_commit_hooks/shfmt
  types: [shell]
  args: ['-l', '-i', '2', '-ci']
  additional_dependencies: [shfmt]
