---
require:
  - rubocop-rails
  - rubocop-performance
  - rubocop-rspec

AllCops:
  Exclude:
    - 'modules/**/*'  # Modules are sync'd from outside repo by r10k
    - 'bin/*'         # binstubs from bundle
  TargetRubyVersion: '2.6'

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'     # RSpec blocks can be large

Style/IfUnlessModifier:
  Exclude:
    - 'Gemfile'       # KISS and avoid diff churn

RSpec/MultipleDescribes:
  Exclude:
    - 'spec/facts/*'  # May have 2 describes

RSpec/DescribeClass:
  Enabled: false

RSpec/NotToNot:
  Enabled: false

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma

Style/WordArray:
  EnforcedStyle: brackets
