#!/bin/bash
set -eEu
set -o pipefail

################################################################################
# Prepare the local dev environment.
# Invoke from the root of the git repo as "ci/bootstrap".
################################################################################

trap finish EXIT

main() {
  :
}

finish() {
  declare -ri RC=$?

  if [[ $RC -eq 0 ]]; then
    echo "$0 OK"
  else
    echo "[ERROR] $0 failed with exit status $RC"
  fi
}

main
