#!/bin/bash
set -eEu
set -o pipefail

################################################################################
# Run the test harness.
# Invoke from the root of the git repo as "ci/test".
################################################################################

. ci/bootstrap

main() {
  run_precommit
  try_precommit
}

run_precommit() {
  info 'Run pre-commit against all files'
  run pre-commit run --all-files --verbose
}

try_precommit() {
  info 'Try local hooks that require prereqs'
  checks='
    fasterer
    reek
    rubocop
  '
  for check in ${checks}; do
    run pre-commit try-repo ./ "${check}" --all-files --verbose
  done
}

main
